techlog_config_path: C:\Program Files\1cv8\conf\logcfg.xml
techlog_archive_script_path: C:\techlog_archive\techlog-archive.ps1
techlog_archive_dir: C:\tech\logs\all
techlog:
  - name: common
    location: "C:\\tech\\logs\\all"
    history: 3
    events:
      - properties:
        - {op: eq, name: Name, value: ADMIN}
      - properties:
        - {op: eq, name: Name, value: CLSTR}
      - properties:
        - {op: eq, name: Name, value: ATTN}
      - properties:
        - {op: eq, name: Name, value: PROC}
      - properties:
        - {op: eq, name: Name, value: CONN}
      - properties:
        - {op: eq, name: Name, value: EXCP}
      - properties:
        - {op: eq, name: Name, value: QERR}
    properties:
      - name: all
  - name: tlock
    location: "C:\\tech\\logs\\all"
    history: 3
    events:
      - properties:
        - {op: eq, name: Name, value: TLOCK}
        - {op: ne, name: WaitConnections, value: ""}
      - properties:
        - {op: eq, name: Name, value: TTIMEOUT}
      - properties:
        - {op: eq, name: Name, value: TDEADLOCK}
    properties:
      - name: all
  - name: longdurationinfo
    location: "C:\\tech\\logs\\all"
    history: 3
    events:
      - properties:
        - {op: ne, name: Name, value: ""}
        - {op: ne, name: Name, value: PROC}
        - {op: ne, name: Name, value: CONN}
        - {op: ne, name: Name, value: TLOCK}
        - {op: gt, name: Duration, value: 10000}
    properties:
      - name: all
      - name: sdbl
        events:
          - {op: eq, name: Name, value: SDBL}
          - {op: ne, name: Func, value: insertRecords}
