all:
  hosts:
    onec-windows-server:
      ansible_host: onec-windows-server.local
    onec-linux-server:
      ansible_host: onec-linux-server.local
  children:
    windows:
      hosts:
        onec-windows-server:
    linux:
      hosts:
        onec-linux-server:
    onec-windows:
      hosts:
        onec-windows-server:
    onec-linux:
      hosts:
        onec-linux-server:
