techlog_config_path: '{{ (ansible_facts["os_family"] == "Windows") | ternary("C:\Program Files\1cv8\conf\logcfg.xml", "/opt/1cv8/conf/logcfg.xml") }}' 
techlog:
  - name: common
    location: '{{ (ansible_facts["os_family"] == "Windows") | ternary("C:\tech\logs\all", "/var/log/1c/all") }}'
    history: 3
    events:
      - properties:
        - {op: eq, name: Name, value: EXCP}
    properties:
      - name: all
